### ISSUE TITLE
Next and Previous button label

### ISSUE THREAD

**Issue by codexorange** [bebraw/react-pagify#7]
Hi, there's something way to change the label of these buttons?, for example, if I want to show a icon using font-awesome.

Thanks.

**Comment by bebraw** [comment]
Now they are fixed. See https://github.com/bebraw/react-pagify/blob/ab862fc3cce3bd46172af12c487c97abbd8fff7a/lib/index.jsx#L73 .

We could make it possible to override them. I.e. instead of

```javascript
<a href='#' onClick={this.preventDefault}>
    Previous
</a>
```

we would have something like

```javascript
{prevButton ? prevButton : <a href='#' onClick={this.preventDefault}>
    Previous
</a>}
```

and the same for `nextButton`.

Do you want to do a PR or should I give it a go?

**Comment by codexorange** [comment]
I've send a PR. Please check

**Comment by bebraw** [comment]
Safe to close.
